website/dashbord/urls.py
from django.urls import path
from .views import dashbord, connexion 

app_name='dashbord'
urlpatterns = [
    path('', dashbord, name='index'),  
    path('connexion/', connexion, name='connexion'),
  


]

website/eleve/urls.py
from django.urls import path
from .views import ajout_eleve, form_ajouEleve ,modifie_eleve ,supprimer_eleve 


app_name='eleve'
urlpatterns = [
    # definir ttes les routes qui sont specifique a l'app
    
    path('', ajout_eleve, name='index'),
    path('form_ajouEleve/', form_ajouEleve, name='add'),
    path('modifie_eleve/<int:id>/', modifie_eleve, name='edit'),
    path('supprimer_eleve/<int:id>/', supprimer_eleve, name='delete'),
    


]

website/professeur/urls.py
from django.urls import path
from .views import professeur,ajoutprofesseur ,modifierProf ,supp_prof


app_name='professeur'
urlpatterns = [
    path('', professeur, name='index'),
    path('ajoutprofesseur/', ajoutprofesseur, name='add'),
    path('modifierProf/<int:id>/', modifierProf, name='edit'),
    path('supp_prof/<int:id>/', supp_prof, name='delete'),
    


]

website/rapport/urls.py
from django.urls import path

from .views import rapport

app_name='rapport'
urlpatterns = [
       path('', rapport, name='index'),
]

website/utilisateur/urls.py
from django.urls import path

from .views import  utilisateur ,ajout_utilisateur ,modi_utilisateur ,suppr_utilisateur

app_name='utilisateur'
urlpatterns = [
       path('', utilisateur, name='index'),
       path('ajout_utilisateur/', ajout_utilisateur, name='add'),
       path('modi_utilisateur/<int:id>/', modi_utilisateur, name='edit'),
       path('supprimer_utilisateur/<int:id>/', suppr_utilisateur, name='delete'),

]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include 
from dashbord import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eleve/', include("eleve.urls")),
    path('dashbord/', include('dashbord.urls')),  
    path('professeur/', include('professeur.urls')),
    path('rapport/', include('rapport.urls')),
    path('utilisateur/', include('utilisateur.urls')),
   
    path('deconnexion/', views.deconnexion, name='deconnexion'),
]

website/dashbord/models.py
from django.db import models

# Create your models here.

website/professeur/models.py
from django.db import models

class Teacher(models.Model):
    name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    age = models.IntegerField()
    courses = models.CharField(max_length=15)
    number = models.CharField(max_length=10)
    ville = models.CharField(max_length=20)

website/rapport/models.py
from django.db import models

# Create your models here.

website/utilisateur/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    pseudo_name = models.CharField(max_length=15)
    password = models.CharField(max_length=225)
    creat_at = models.DateTimeField(auto_now_add=True)

website/professeur/forms.py
from django import forms
from .models import Teacher

class TeacherForm(forms.Form):
    nom = forms.CharField(label='Nom', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nom'}))
    prenom = forms.CharField(label='Prénom', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Prénom'}))
    
    MATIERE_CHOICES = [
        ('Maths', 'Maths'),
        ('Physique', 'Physique'),
        ('EPS', 'EPS'),
        ('Anglais', 'Anglais'),
        ('SVT', 'SVT'),
        ('français', 'Français'),
        ('philosophie', 'Philosophie'),
    ]
    matiere = forms.ChoiceField(label='Sélectionner une matière', choices=MATIERE_CHOICES)
    
    age = forms.IntegerField(label='Âge')
    telephone = forms.CharField(label='Téléphone', max_length=15)
    ville = forms.CharField(label='Ville', max_length=100)
    
    
class TeacherModelForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', 'last_name', 'age', 'courses', 'number', 'ville']  
        labels = {
            'name': 'Nom',
            'last_name': 'Prénom',
             'age': 'Âge',
            'courses': 'Matière',
            'number': 'Téléphone',
            'ville': 'Ville',
        }
        widgets = {
            
            'courses': forms.Select(choices=[
                ('Maths', 'Maths'),
                ('Physique', 'Physique'),
                ('EPS', 'EPS'),
                ('Anglais', 'Anglais'),
                ('SVT', 'SVT'),
                ('français', 'Français'),
                ('philosophie', 'Philosophie'),
            ]),
        }

website/utilisateur/forms.py
from django import forms
from .models import User

class MyForm(forms.Form):
    pseudo_name = forms.CharField(max_length=15)
    password = forms.CharField(max_length=225)
    creat_at = forms.DateTimeField()

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['pseudo_name', 'password', 'creat_at']
        exclude = ['creat_at']  



website/dashbord/views.py
from django.shortcuts import render

def dashbord(request):
    return render(request, "dashbord.html")


def connexion(request):
    return render(request, "connexion.html")



def deconnexion(request):
    return render(request, "deconnexion.html")

website/professeur/views.py
from django.shortcuts import render ,get_object_or_404 ,redirect 
from .forms import TeacherForm , Teacher,TeacherModelForm
from django.contrib import messages

# Create your views here.

def professeur(request):
    professeurs = Teacher.objects.all()  # Utilisez le modèle Teacher pour récupérer tous les enseignants
    context = {'professeurs': professeurs}  
    return render(request, "professeur.html", context)


def ajoutprofesseur(request):
    if request.method == 'POST':
        form = TeacherModelForm(request.POST)
        if form.is_valid():
           
            form.save()
            
            
    else:
        form = TeacherModelForm()

    return render(request, 'ajoutprofesseur.html', {'form': form})



def modifierProf(request, id):
    user = get_object_or_404(Teacher, id=id)  

    
    context = {
        "title": "Modifier professeur"
    }

    if request.method == "POST":
        form = TeacherModelForm(request.POST, instance=user)  
        if form.is_valid():
            form.save()
            return redirect('professeur:index')  
    else:
        form = TeacherModelForm(instance=user) 
    
    
    context['form'] = form

    return render(request, "modifierProf.html", context)




def supp_prof(request, id):
    user = get_object_or_404(Teacher, id=id)
    user.delete()
    messages.success(request, "Professeur supprimé avec succès!")
    return redirect('professeur:index')


website/rapport/views.py
from django.shortcuts import render

# Create your views here.


def rapport(request):
    return render(request, "rapport.html")

website/utilisateur/views.py
from django.shortcuts import render , get_object_or_404,redirect
from .forms import UserForm , User
from django.contrib import messages

# Create your views here.
def utilisateur(request):
    users = User.objects.all()

    context = {'users': users}
    return render(request, "utilisateur.html", context)


def ajout_utilisateur(request):
    if request.method == 'POST':  
        form = UserForm(request.POST)
        if form.is_valid():  
            form.save()  
            return redirect('utilisateur:index')
            
    else:
        form = UserForm()  

    context = {'form': form}
    return render(request, "ajout_utilisateur.html", context)




def modi_utilisateur(request, id):
    user = get_object_or_404(User, id=id)  

    
    context = {
        "title": "Modifier utilisateur"
    }

    if request.method == "POST":
        form = UserForm(request.POST, instance=user)  
        if form.is_valid():
            form.save()
            return redirect('utilisateur:index')  
    else:
        form = UserForm(instance=user) 
    
    
    context['form'] = form

    return render(request, "modi_utilisateur.html", context)


def suppr_utilisateur(request, id):
    user = get_object_or_404(User, id=id)
    user.delete()
    messages.success(request, "Utilisateur supprimé avec succès!")
    return redirect('utilisateur:index')

website/templates/ajout_eleve.html
{% extends 'base.html' %}

{% block title %}Gestion des élèves{% endblock %}
    
{% block content %}
    <div class="eleve">
        <div class="elevemin"><h2>Élèves(2)</h2></div>
        <a href="{% url 'eleve:add' %}" class="elevemin">
            <h2>+ Nouvel élève</h2>
        </a>
    </div>
    <div class="eleve1">
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        
                        <th>Genre</th>
                        <th>Classe</th>
                        <th>Matricule</th>
                        <th>Age</th>
                        <th>Telephone</th>
                        <th>Ville</th>
                        <th>Action</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for eleve in eleves %}
                    <tr>
                        
                        <td>{{ eleve.last_name }}</td>
                        <td>{{ eleve.first_name }}</td>
                        <td>{{ eleve.gender }}</td> 
                        <td>{{ eleve.scholarship }}</td> 
                        <td>{{ eleve.matricula }}</td>
                        <td>{{ eleve.age }}</td>
                        <td>{{ eleve.phone }}</td>
                        <td>{{ eleve.country }}</td>
                        <td>
                            <a href="{% url 'eleve:edit' eleve.id %}" class="btn-link">
                                <button class="btn-modify">Modifier</button>
                            </a>
                            <a href="{% url 'eleve:delete' eleve.id %}" class="btn-link" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet eleve ?');">
                                <button class="btn-delete">Supprimer</button>
                            </a>
                        </td>
                        
                                   
                    </tr>
                    {% empty %}
                   
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}


website/templates/ajout_utilisateur.html
{% extends 'base.html' %}

{% block title %}Modifier Utilisateur{% endblock %}

{% block content %}

        <div class="sidebar-container2">
            <div class="utilisateur">
                <a href="{% url 'utilisateur:index' %}" class="link-container">
                    <div class="uti1">
                        <i class="fas fa-arrow-left"></i> 
                        <span>Retour</span>
                    </div>
                </a>
                <div class="uti2">
                    <div id="id_utilisateur-form-container">
                        <h2 id="id_utilisateur-form-title">Ajouter utilisateurs</h2>
                        <form id="id_utilisateur-form" method="post">
                            {% csrf_token %}
                            {{ form }}  
                        
                            <div id="id_utilisateur-button-group">
                                <a href="{% url 'utilisateur:index' %}" id="id_utilisateur-cancel-button" class="btn-annuler">Annuler</a>
                                <button type="submit" id="id_utilisateur-submit-button">Enregistrer</button>
                            </div>
                        </form>
                        
                    </div>
                </div>
                
            </div>
        </div>
       
        {% endblock %}


website/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar-container">
        <div class="sidebar-container1">
            {% block sidebar %}
            <div class="sidebar1"></div>
            <div class="sidebar2">
                <div class="side1">
                    <a href="{% url 'dashbord:index' %}" class="side1">
                    <i class="fas fa-tachometer-alt" style="font-size: 24px; margin-right: 10px;"></i> 
                    <span style="font-size: 16px;">Tableau de bord</span>
                    </a>
                </div>
                <a href="{% url 'eleve:index' %}" class="side1">
                    <i class="fas fa-user-graduate"></i>
                    <span>Élèves</span>
                </a>
                <a href="{% url 'professeur:index' %}" class="side1">
                    <i class="fas fa-chalkboard-teacher"></i>
                    <span>Professeurs</span>
                </a>
                <a href="{% url 'utilisateur:index' %}" class="side1">
                    <i class="fas fa-users"></i>
                    <span>Utilisateurs</span>
                </a>
                <a href="{% url 'rapport:index' %}" class="side1">
                    <i class="fas fa-file-alt"></i>
                    <span>Rapports</span>
                </a>
            </div>
            <div class="sidebar3">
                <i class="fas fa-sign-out-alt"></i>
                <span>Déconnexion</span>
            </div>
            {% endblock %}
        </div>

        <div class="sidebar-container2">
            {% block content %} {% endblock %}
            
            
        </div>
    </div>
    <!-- <script src="{% static 'js/script.js' %}"></script> -->
</body>
</html>

website/templates/connexion.html

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <form class="login-form">
            <div class="container-img">
                <img src="{% static 'img/Capture ico.png' %}" alt="Logo">

            </div>
            <div class="input-group">
                <label for="identifiant">Identifiant</label>
                <input type="text" id="identifiant" name="identifiant" required>
            </div>
            <div class="input-group">
                <label for="motdepasse">Mot de passe</label>
                <input type="password" id="motdepasse" name="motdepasse" required>
            </div>
            <a href="{% url 'dashbord:index' %}" class="btn-connexion">Connexion</a>

        </form>
    </div>
</body>
</html>


website/templates/dashbord.html
{% extends 'base.html' %}

{% block title %} dashbord{% endblock %}

{% block content %}
        <div class="sidebar-container2">
            <div class="right1">
                <h1>Tableau de bord</h1>
            </div>
            <div class="right2">
                <div class="right2min">
                    <div class="part1"> <h3>Nombre d'élève</h3></div>
                    <div class="part2"> <h1>128 000</h1></div>
                </div>
                <div class="right2min">
                    <div class="part1"> <h3>Nombre de professeur</h3></div>
                    <div class="part2"> <h1>128 000</h1></div>
                </div>
            </div>
            <!-- div -->
             <div class="espace"></div>
            <div class="right2">
                <div class="right2min">
                    <div class="part1"> <h3>Nombre d'utilisateur</h3></div>
                    <div class="part2"> <h1>128 000</h1></div>
                </div>
                <div class="right2min">
                    <div class="part1"> 
                        <h3>Elève par genre</h3>
                    </div>
                    <div class="part2">
                        <div class="legend">
                            <div class="legend-item">
                                <button class="color-button rose"></button>
                                <span class="label">Femme</span>
                            </div>
                            <div class="legend-item">
                                <button class="color-button bleu"></button>
                                <span class="label">Homme</span>
                            </div>
                        </div>
                       <div class="circle-container">
                            <div class="circle"></div>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    
{% endblock %}


website/templates/deconnexion.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Déconnexion</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <form class="logout-form">
            <div class="logout-message">
                <h2>Voulez-vous vraiment vous déconnecter ?</h2>
            </div>
            <div class="btn-group">
                <!-- Lien vers la déconnexion -->
                <a href="{% url 'connexion' %}" class="btn-logout">Oui, me déconnecter</a>
                <!-- Lien pour annuler la déconnexion et retourner au tableau de bord -->
                <a href="{% url 'dashbord' %}" class="btn-cancel">Annuler</a>
            </div>
        </form>
    </div>
</body>
</html>

website/templates/form_ajouEleve.html
{% extends 'base.html' %}

{% block title %}ajouter un eleve{% endblock %}

{% block content %}
<div class="elevepage1">
    <a href="{% url 'eleve:index' %}" class="elevepage1min">
        <i class="fas fa-arrow-left"></i>
        <span>Retour</span>
    </a>

    <div class="elevepage1min2">
        <h2>Ajouter un élève</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" name="enregistrer">Enregistrer</button>
            <a href="{% url 'eleve:index' %}" class="btn-cancel">Annuler</a>
        </form>
        
        
    </div>
</div>
{% endblock %}

website/templates/modi_utilisateur.html
{% extends 'base.html' %}

{% block title %}Modifier Utilisateur{% endblock %}

{% block content %}
<div class="elevepage1">
    <a href="{% url 'utilisateur:index' %}" class="elevepage1min">
        <i class="fas fa-arrow-left"></i>
        <span>Retour</span>
    </a>

    <div class="elevepage1min2">
        <h2>Modifier un utilisateur</h2>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <div class="form-buttons">
                <a href="{% url 'utilisateur:index' %}" class="btn-cancel">Annuler</a>
                <button type="submit" class="btn-save">Enregistrer</button>
            </div>
        </form>
        
    </div>
</div>
{% endblock %}

website/templates/modifie_eleve.html
{% extends 'base.html' %}

{% block title %}ajouter un eleve{% endblock %}

{% block content %}


    <div class="sidebar-container2">
        <div class="elevepage1">
            <div class="elevepage1min">
                <a href="{% url 'eleve:index' %}" class="elevepage1min">
                    <i class="fas fa-arrow-left"></i>
                    <span>retour</span>
                </a>
            </div>
            <div class="elevepage1min2">
                <h2>Modifier l'eleve - 245</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-buttons">
                        <a href="{% url 'eleve:index' %}" class="btn-cancel">Annuler</a>
                        <button type="submit" class="btn-save">Enregistrer</button>
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}



website/templates/modifierProf.html
{% extends 'base.html' %}

{% block title %}Modifier professeur{% endblock %}

{% block content %}

<div class="sidebar-container2">
    <div class="elevepage1">
        <a href="{% url 'professeur:index' %}" class="elevepage1min">
            <i class="fas fa-arrow-left"></i>
            <span>Retour</span>
        </a>
        
        <div class="elevepage1min2">
            <h2>Modifier un professeur - {{ professeur.id }}</h2>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <div class="form-buttons">
                    <a href="{% url 'professeur:index' %}" class="btn-cancel">Annuler</a>
                    <button type="submit" class="btn-save">Enregistrer</button>
                </div>
            </form>
        </div>
        
    </div>
</div>

{% endblock %}

website/templates/professeur.html
{% extends 'base.html' %}

{% block title %} Professeurs{% endblock %}

{% block content %}
        <div class="sidebar-container2">
            <div class="eleve">
                <div class="elevemin"><h2>Professeurs(2)</h2></div>
                <a href="{% url 'professeur:add' %}" class="elevemin">
                    <h2>+ Nouveau professeur</h2>
                </a>
                
            </div>
            <div class="eleve1">
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénoms</th>
                                <th>Matière</th>
                                
                                <th>Âge</th>
                                <th>Téléphone</th>
                                <th>Ville</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for professeur in professeurs %}
                            <tr>
                                <td>{{ professeur.name }}</td>
                                <td>{{ professeur.last_name }}</td>
                                <td>{{ professeur.courses }}</td>
                                <td>{{ professeur.age }} </td>
                                <td>{{ professeur.number }}</td>
                                <td>{{ professeur.ville }}</td>
                                
                                
                                <td>
                                    <a href="{% url 'professeur:edit' professeur.id %}" class="btn-link">
                                        <button class="btn-modify">Modifier</button>
                                    </a>
                                    
                                    <a href="{% url 'professeur:delete' professeur.id %}" class="btn-link" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet professeur ?');">
                                        <button class="btn-delete">Supprimer</button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    
                </div>
            </div>
            <div class="eleve2"></div>
        </div>
       
   


    {%endblock%}

website/templates/rapport.html
{% extends 'base.html' %}

{% block title %} Modifier professeur{% endblock %}

{% block content %}


        <div class="sidebar-container2">
            
            <div class="rapport-container">
                <h2 id="rapport-title">Rapport</h2>
                <form id="rapport-form">
                    <div class="rapport-select-group">
                        <label for="rapport-options"></label>
                        <select id="rapport-options">
                            <option value="" disabled selected>Sélectionner une option</option>
                            <option value="eleves">Liste des élèves</option>
                            <option value="professeurs">Liste des professeurs</option>
                            <option value="utilisateurs">Liste des utilisateurs</option>
                        </select>
                    </div>
                    <div id="rapport-button-group">
                        <button type="button" id="rapport-pdf-button">Générer format PDF</button>
                        <button type="button" id="rapport-excel-button">Générer format Excel</button>
                    </div>
                </form>
            </div>
        </div>
       
{% endblock %}

website/templates/supp_prof.html
{% extends 'base.html' %}

{% block title %} Modifier professeur{% endblock %}

{% block content %}


        <div class="sidebar-container2">
            <div class="eleve">
                <div class="elevemin"><h2>Professeurs(2)</h2></div>
                <div class="elevemin"><h2> + Nouveau professeur</h2></div>
            </div>
            <div class="eleve1">
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénoms</th>
                                <th>Matière</th>
                                <th>Vacant</th>
                                
                                <th>Âge</th>
                                <th>Téléphone</th>
                                <th>Ville</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Kouakou</td>
                                <td>Gregoire</td>
                                <td>Math</td>
                                <td>Non</td>
                               
                                <td>40</td>
                                <td>0123456789</td>
                                <td>Touba</td>
                                <td>
                                    <button class="btn-modify">Modifier</button>
                                    <button class="btn-delete">Supprimer</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Atta</td>
                                <td>Flora</td>
                                <td>Physique</td>
                                <td>Oui</td>
                               
                                <td>37</td>
                                <td>0987654321</td>
                                <td>Bouaké</td>
                                <td>
                                    <button class="btn-modify">Modifier</button>
                                    <button class="btn-delete">Supprimer</button>
                                </td>
                            </tr>
                          
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="eleve2"></div>
        </div>
       

{% endblock %}

website/templates/supprimer_eleve.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar-container">
        <div class="sidebar-container1">
            <div class="sidebar1"></div> <!-- ok -->
            <div class="sidebar2">
                <div class="side1">
                    <a href="{% url 'dashbord:index' %}" class="side1">
                        <i class="fas fa-tachometer-alt" style="font-size: 24px; margin-right: 10px;"></i> 
                        <span style="font-size: 16px;">Tableau de bord</span>
                    </a>
                </div>
                <a href="{% url 'eleve:index' %}" class="side1">
                    <i class="fas fa-user-graduate"></i> <!-- Icône pour "Élève" -->
                    <span>Élèves</span>
                </a>
                <a href="{% url 'professeur:index' %}" class="side1">
                    <i class="fas fa-chalkboard-teacher"></i> <!-- Icône pour "Professeur" -->
                    <span>Professeurs</span>
                </a>
                <a href="{% url 'utilisateur:index' %}" class="side1">
                    <i class="fas fa-users"></i> <!-- Icône pour "Utilisateur" -->
                    <span>Utilisateurs</span>
                </a>
                <a href="{% url 'rapport:index' %}" class="side1">
                    <i class="fas fa-file-alt"></i> <!-- Icône pour "Rapport" -->
                    <span>Rapports</span>
                </a>
            </div>
            <div class="sidebar3">
                <i class="fas fa-sign-out-alt"></i> <!-- Icône pour "Déconnexion" -->
                <span>Déconnexion</span>
            </div>
        </div>

        <div class="sidebar-container2">
            {% block content %}
            <!-- Le contenu spécifique à chaque page sera inséré ici -->
            {% endblock %}
        </div>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>